# ╭─────────────────────────────────ImplementationGuide-fish.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  https://fshschool.org/docs/sushi/configuration/#full-configuration                            │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
instanceOptions:
  setMetaProfile: never
  manualSliceOrdering: true
id: davinci-crd
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 2
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: fm
canonical: http://hl7.org/fhir/us/davinci-crd
version: 2.1.0-preview
name: CoverageRequirementsDiscovery
title: Da Vinci - Coverage Requirements Discovery
status: active
experimental: false
publisher:
  name: HL7 International / Financial Management
contact:
    telecom:
      - system: url
        value: http://www.hl7.org/Special/committees/fm
description:  Guidelines for conveying coverage requirements to clinicians when planning treatment
jurisdiction: urn:iso:std:iso:3166#US
packageId: hl7.fhir.us.davinci-crd
license: CC0-1.0
fhirVersion: 4.0.1
parameters:
  path-expansion-params: "../../input/terminology-settings.json"
  apply-publisher: true
  apply-contact: true
  globals-in-artifacts: true
  version-comparison: 2.0.0

#  path-binary: input/hooks-files
    
copyrightYear: 2019+
releaseLabel: STU 2


# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
dependencies:
  hl7.terminology:
    version: 6.0.2
    uri: http://terminology.hl7.org/ImplementationGuide/hl7.terminology
    id: tx
    reason: |
      Shared terminology used across HL7 specifications
  hl7.fhir.us.core.v311:
    version: 3.1.1
    uri: http://hl7.org/fhir/us/core/ImplementationGuide/hl7.fhir.us.core
    id: uscore3
    reason: |
      Defines USCDI v1 EHR expectations on a range of resources that will be passed to and/or queried by CRD servers.  
  hl7.fhir.us.core:
    id: uscore6
    version: 6.1.0
    reason: |
      Defines USCDI v3 EHR expectations on a range of resources that will be passed to and/or queried by CRD servers
  hl7.fhir.us.core.v700:
    version: 7.0.0
    uri: http://hl7.org/fhir/us/core/ImplementationGuide/hl7.fhir.us.core
    id: uscore7
    reason: |
      Defines USCDI v4 EHR expectations on a range of resources that will be passed to and/or queried by CRD servers.  
  hl7.fhir.uv.sdc:
    id: sdc
    version: 3.0.0
    reason: |
      Defines expecations for Questionnaires prompted for by cards
  hl7.fhir.us.davinci-hrex:
    id: hrex
    version: 1.1.0-ballot
    reason: |
      Defines common conformance rules across all Da Vinci IGs, as well as additional constraints and profiles beyond U.S. Core
  hl7.fhir.extensions.r5:
    id: r5ext
    version: 4.0.1
    reason: |
      Makes available certain R5 elements for use as part of this R4 IG
  us.nlm.vsac:
    id: vsac
    uri: 'http://fhir.org/packages/us.nlm.vsac/ImplementationGuide/us.nlm.vsac'
    version: 0.19.0
    reason: |
      Defines some of the US Core value set bound to in this IG
  hl7.fhir.uv.tools:
    id: tools
    uri: 'http://hl7.org/fhir/tools/ImplementationGuide/hl7.fhir.uv.tools'
    version: current
    reason: |
      Defines CDS Hooks structures leveraged in the validation of this IG
pages:
  index.md:
    title: CRD IG Home Page
  usecases.md:
    title: Use Cases and Overview
  background.md:
    title: Technical Background
  epa.md:
    title: ePA Coordinators
  foundation.md:
    title: Foundational Requirements
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: trial-use
  security.md:
    title: Privacy, Security, and Safety
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: trial-use
  deviations.md:
    title: CDS Hook Deviations and Enhancements
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: trial-use
  hooks.md:
    title: Supported Hooks
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: trial-use
  cards.md:
    title: CDS Hook Response Profiles
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: trial-use
  implementation.md:
    title: Implementation Considerations
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: trial-use
  metrics.md:
    title: CRD Metrics
  allartifacts.md:
    title: FHIR Artifacts
    artifacts.html:
      title: Artifact List
  downloads.md:
    title: Downloads
  credits.md:
    title: Credits
  history.md:
    title: Change History
groups:
  - str-logicalmodel-hooks:
    name: "Structures: CDS Hooks Extensions"
    description: "Models that define extensions on CDS Hooks JSON structures"
    resources:
      - CDSHookServicesExtensionConfiguration
      - CDSHookServiceResponseExtensionIfNoneExist
      - CDSHookServiceResponseExtensionAssociatedResource
      - CDSHookServiceRequestExtensionRequestConfig
resources:
  Encounter/example:
    extension:
      - url: http://hl7.org/fhir/5.0/StructureDefinition/extension-ImplementationGuide.definition.resource.profile
        valueCanonical: http://hl7.org/fhir/us/davinci-crd/StructureDefinition/profile-encounter3.1
  Binary/CRDServices:
    name: "Example CRD Services Response"
    description: "An example of a CRD services response"
    extension:
      - url: http://hl7.org/fhir/tools/StructureDefinition/implementationguide-resource-format
        valueCode: application/json
      - url: http://hl7.org/fhir/tools/StructureDefinition/implementationguide-resource-logical
        valueCanonical: http://hl7.org/fhir/tools/StructureDefinition/CDSHooksServices
  Binary/CRDServiceRequest:
    name: "Example CRD Service Requestion with MedicationRequests"
    description: "An example of a CRD request for order-sign with MedicationRequests"
    extension:
      - url: http://hl7.org/fhir/tools/StructureDefinition/implementationguide-resource-format
        valueCode: application/json
      - url: http://hl7.org/fhir/tools/StructureDefinition/implementationguide-resource-logical
        valueCanonical: http://hl7.org/fhir/tools/StructureDefinition/CDSHooksRequest
  Binary/CRDServiceRequest2:
    name: "Example CRD Service Request with ServiceRequests"
    description: "An example of a CRD request for order-sign with ServiceRequests"
    extension:
      - url: http://hl7.org/fhir/tools/StructureDefinition/implementationguide-resource-format
        valueCode: application/json
      - url: http://hl7.org/fhir/tools/StructureDefinition/implementationguide-resource-logical
        valueCanonical: http://hl7.org/fhir/tools/StructureDefinition/CDSHooksRequest
  Binary/CRDServiceResponse:
    name: "Example CRD Service Response"
    description: "An example of a CRD response with links"
    extension:
      - url: http://hl7.org/fhir/tools/StructureDefinition/implementationguide-resource-format
        valueCode: application/json
      - url: http://hl7.org/fhir/tools/StructureDefinition/implementationguide-resource-logical
        valueCanonical: http://hl7.org/fhir/tools/StructureDefinition/CDSHooksResponse
  Binary/CRDServiceResponse2:
    name: "Example CRD Service Response - Coverage Information"
    description: "An example CRD response with Coverage Information extension"
    extension:
      - url: http://hl7.org/fhir/tools/StructureDefinition/implementationguide-resource-format
        valueCode: application/json
      - url: http://hl7.org/fhir/tools/StructureDefinition/implementationguide-resource-logical
        valueCanonical: http://hl7.org/fhir/tools/StructureDefinition/CDSHooksResponse
  Bundle/search-request:
    name: "Example EHR search"
    description: "Sample of an CRD service searching an EHR that does not support prefetch"
  Bundle/search-response:
    name: "Example EHR response"
    description: "The response to a CRD service query for information not returned in prefetch"
