# ╭─────────────────────────────────ImplementationGuide-fish.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  https://fshschool.org/docs/sushi/configuration/#full-configuration                            │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
instanceOptions:
  setMetaProfile: never
  manualSliceOrdering: true
id: davinci-crd
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 3
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: fm
canonical: http://hl7.org/fhir/us/davinci-crd
version: 2.2.0-cibuild
name: CoverageRequirementsDiscovery
title: Da Vinci - Coverage Requirements Discovery
status: active
experimental: false
publisher:
  name: HL7 International / Financial Management
contact:
    telecom:
      - system: url
        value: http://www.hl7.org/Special/committees/fm
description:  Guidelines for conveying coverage requirements to clinicians when planning treatment
jurisdiction: urn:iso:std:iso:3166#US
packageId: hl7.fhir.us.davinci-crd
license: CC0-1.0
fhirVersion: 4.0.1
parameters:
  path-expansion-params: "../../input/terminology-settings.json"
  auto-oid-root: 2.16.840.1.113883.4.642.40.18
  apply-publisher: true
  apply-contact: true
  globals-in-artifacts: true
  pin-canonicals: pin-multiples
  version-comparison: 
   - 2.1.0
  shownav: true

#  path-binary: input/hooks-files
    
copyrightYear: 2019+
releaseLabel: STU 2.1


# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
dependencies:
  hl7.fhir.us.core:
    id: uscore7
    version: 7.0.0
    uri: http://hl7.org/fhir/us/core/ImplementationGuide/hl7.fhir.us.core
    reason: |
      Defines USCDI v4 EHR expectations on a range of resources that will be passed to and/or queried by CRD servers.  
  hl7.fhir.us.core.v610:
    id: uscore6
    version: 6.1.0
    uri: http://hl7.org/fhir/us/core/v610/ImplementationGuide/hl7.fhir.us.core.v610
    reason: |
      Defines USCDI v3 EHR expectations on a range of resources that will be passed to and/or queried by CRD servers
  hl7.fhir.us.core.v311:
    id: uscore3
    version: 3.1.1
    uri: http://hl7.org/fhir/us/core/v311/ImplementationGuide/hl7.fhir.us.core.v311
    reason: |
      Defines USCDI v1 EHR expectations on a range of resources that will be passed to and/or queried by CRD servers.  
  hl7.fhir.uv.sdc:
    id: sdc
    version: 3.0.0
    reason: |
      Defines expectations for Questionnaires prompted for by cards
  hl7.fhir.us.davinci-hrex:
    id: hrex
    version: 1.1.0
    reason: |
      Defines common conformance rules across all Da Vinci IGs, as well as additional constraints and profiles beyond U.S. Core
  hl7.fhir.extensions.r5:
    id: r5ext
    version: 4.0.1
    reason: |
      Makes available certain R5 elements for use as part of this R4 IG
  us.nlm.vsac:
    id: vsac
    uri: http://fhir.org/packages/us.nlm.vsac/ImplementationGuide/us.nlm.vsac
    version: 0.19.0
    reason: |
      Uses the latest version of the VSAC codes
  hl7.fhir.uv.tools:
    id: tools
    uri: http://hl7.org/fhir/tools/ImplementationGuide/hl7.fhir.uv.tools
    version: current
    reason: |
      Defines the CDS Hooks logical models
pages:
  index.md:
    title: CRD IG Home Page
  background.md:
    title: Reading this IG
  usecases.md:
    title: Use Cases
  credits.md:
    title: Project and Participants
  burden.md:
    title: Burden Reduction
  epa.md:
    title: ePA Coordinators
  conformance.md:
    title: Conformance Expectations
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: trial-use
  security.md:
    title: Privacy, Safety, and Security
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: trial-use
  foundation.md:
    title: Foundational Requirements
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: trial-use
  deviations.md:
    title: CDS Hook Deviations and Enhancements
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: trial-use
  hooks.md:
    title: Supported Hooks
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: trial-use
  cards.md:
    title: CDS Hook Response Profiles
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: trial-use
  implementation.md:
    title: Implementation Considerations
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: trial-use
  metrics.md:
    title: CRD Metrics
  allartifacts.md:
    title: FHIR Artifacts
    artifacts.html:
      title: Artifact List
  downloads.md:
    title: Downloads
  history.md:
    title: Change History
groups:
  -str-logicalmodel-hooks:
    name: "Structures: CDS Hooks Extensions"
    description: "Models that define extensions on CDS Hooks JSON structures"
    resources:
      - CDSHookServicesExtensionConfiguration
      - CDSHookServiceResponseExtensionIfNoneExist
      - CDSHookServiceResponseExtensionAssociatedResource
      - CDSHookServiceRequestExtensionRequestConfig
  -ex-example-hooks:
    name: "Example: CDS Hooks Examples"
    description: "Examples of CDS Hooks JSON instances"
resources:
  Binary/CRDServices:
    groupingId: "-ex-example-hooks"
    name: "Example CRD Services Response"
    description: "An example of a CRD services response"
    extension:
      - url: http://hl7.org/fhir/tools/StructureDefinition/implementationguide-resource-format
        valueCode: application/json
      - url: http://hl7.org/fhir/tools/StructureDefinition/implementationguide-resource-logical
        valueCanonical: http://hl7.org/fhir/tools/StructureDefinition/CDSHooksServices
  Binary/CRDServiceRequest:
    groupingId: "-ex-example-hooks"
    name: "Example CRD Service Requestion with ServiceRequests"
    description: "An example of a CRD request for order-sign with ServiceRequests"
    extension:
      - url: http://hl7.org/fhir/tools/StructureDefinition/implementationguide-resource-format
        valueCode: application/json
      - url: http://hl7.org/fhir/tools/StructureDefinition/implementationguide-resource-logical
        valueCanonical: http://hl7.org/fhir/tools/StructureDefinition/CDSHooksRequest
  Binary/CRDServiceRequest2:
    groupingId: "-ex-example-hooks"
    name: "Example CRD Service Request with MedicationRequests"
    description: "An example of a CRD request for order-sign with MedicationRequests"
    extension:
      - url: http://hl7.org/fhir/tools/StructureDefinition/implementationguide-resource-format
        valueCode: application/json
      - url: http://hl7.org/fhir/tools/StructureDefinition/implementationguide-resource-logical
        valueCanonical: http://hl7.org/fhir/tools/StructureDefinition/CDSHooksRequest
  Binary/CRDServiceResponse:
    groupingId: "-ex-example-hooks"
    name: "Example CRD Service Response"
    description: "An example of a CRD response all 'mustSupport' response types, plus 'change order' response type"
    extension:
      - url: http://hl7.org/fhir/tools/StructureDefinition/implementationguide-resource-format
        valueCode: application/json
      - url: http://hl7.org/fhir/tools/StructureDefinition/implementationguide-resource-logical
        valueCanonical: http://hl7.org/fhir/tools/StructureDefinition/CDSHooksResponse
  Binary/CRDServiceResponse2:
    groupingId: "-ex-example-hooks"
    name: "Example CRD Service Response - optional responses"
    description: "An example CRD response with various optional response types"
    extension:
      - url: http://hl7.org/fhir/tools/StructureDefinition/implementationguide-resource-format
        valueCode: application/json
      - url: http://hl7.org/fhir/tools/StructureDefinition/implementationguide-resource-logical
        valueCanonical: http://hl7.org/fhir/tools/StructureDefinition/CDSHooksResponse
  Bundle/search-request:
    name: "Example EHR search"
    description: "Sample of an CRD service searching an EHR that does not support prefetch"
  Bundle/search-response:
    name: "Example EHR response"
    description: "The response to a CRD service query for information not returned in prefetch"

